branches:
  only:
    - master
    - develop
    - travisci

language: c

install:
  - sudo apt-get install mono-devel mono-gmcs nunit-console

script:
  - ./.travis/PackageRestore.sh
  - ./.travis/RunBuild.sh
